### ISSUE TITLE
WebView window don't appers on windows

### ISSUE THREAD

**Issue by DoctorVWA** [Boscop/web-view#14]
the process keeps running but no window with the content, I tryed the examples/minimal.rs

**Comment by Boscop** [comment]
[> Note: For some reason (at least on Windows), if I try to cargo run the examples directly, they don't show the window, but it works with cargo build --example <name> && target\debug\examples\<name>
](https://github.com/Boscop/web-view/tree/master/examples)

Not sure why it happens but that's the current workaround..
I think it's because cargo assumes that the exe uses the console subsystem..

**Comment by DoctorVWA** [comment]
Hum, that's right, if I run the exe manually it works, so ok, I think I can close the issue, if you don't need it open to fix this "problem"

**Comment by DoctorVWA** [comment]
But thanks bro, looks like that lib I will not be able to use, the application what I'm doing needs to use very low cpu and memory, it takes a lot to process the page, thanks for all the help, bye.

**Comment by galich** [comment]
I've stumbled upon the same problem, fix is here https://github.com/Boscop/web-view/pull/16
