### ISSUE TITLE
Build on Windows broken due to subcrate tinyfiledialogs

### ISSUE THREAD

**Issue by gin66** [Boscop/web-view#153]
How about switching to nativefiledialog-sys ?

**Comment by zxey** [comment]
I do not think that `nativefiledialog-sys` would help, have you tried it? - It is similar to tinyfiledialogs, it's also bindings to c library.
Can you post more info, compilation log, why it failed?

**Comment by gin66** [comment]
The broken build for windows is reported in your travis-build. I am not using windows, but a broken build should be resolved. So I have checked in the Internet for the build error and apparently this is due to printf and Visual Studio lib version (or so). The crate itself does not mention windows compatibility and nativefiledialog-sys would be a contender to try.

Anyway, the travis-build has been dropped and so can this issue.  No need to waste time on windows compatibility, if not needed.

BTW: I would advise to remove filedialog completely, because it has nothing to do with web-view.

**Comment by zxey** [comment]
web-view builds with fine x86_64-pc-windows-msvc, the problem is x86_64-pc-windows-gnu, travis did not have some tools needed to build native c libraries, but if you have them it should also build correctly.

The plan is to drop dialog support in next version and delegate that functionality to different crates, I already deprecated this functionality.
