### ISSUE TITLE
add a discussion/question space

### ISSUE THREAD

**Issue by zee-mzha** [Boscop/web-view#242]
This project is really great but a big issue is that there's a lack of resources. It's kind of hard to find answers to questions about how to use this library, whenever I try to google for answers I end up getting results about android or Microsoft's webview2. Having a comprehensive wiki or guide is hard, so in the meantime I feel like it would make sense to add some kind of discussion space. I've seen a lot of projects in the rust gui space using zulip for example, or discord or anything along those lines.

**Comment by Blakeinstein** [comment]
This project offers only a method of presenting a webpage as an app. The html you provide, either via localhost, a web address or as a string will be rendered out in a window. Ideally you would look at examples on how to achieve this. Even then should you have any queries, feel free to open an issue, and if no one responds feel free to ping me as well! Having a discussion platform, is kind of unwarranted at the moment, unless the scope of the project expands.

I will let @zxey decide.

**Comment by zxey** [comment]
I agree if you have a question you can open up an issue. I like issues because it allows me to get any question/issue at a pace that does not eat up too much of my time, if we were to use zulip/discrord/whatever I would be almost always available and that would put a lot of pressure on me which I do not want.

I am not opposed to having discussion platform when the community around this project gets bigger and more people than me can answer questions.

I am closing this issue, but feel free to open up more, if you have any questions.
