### ISSUE TITLE
Crash when loading local file (EdgeHTML)

### ISSUE THREAD

**Issue by Regentag** [Boscop/web-view#259]
When using the EdgeHTML feature, a crash occurs when trying to load a local HTML file.

When using MSHTML, it loads without problems.

My source code:
```rust
fn main() {
    web_view::builder()
        .title("Minimal webview example")
        .content(Content::Url("file:///C:/Users/Regentag/Desktop/DEV/webview-example/test.html"))
        //.content(Content::Url("https://namu.wiki"))
        .size(800, 600)
        .resizable(true)
        .debug(true)
        .user_data(())
        .invoke_handler(|_webview, _arg| Ok(()))
        .run()
        .unwrap();
}
```

test.html
```html
<h1>TEST TEST TEST</h1>
```

error:
```rust
C:\Users\Regentag\Desktop\DEV\webview-example>cargo run
   Compiling webview-example v0.1.0 (C:\Users\Regentag\Desktop\DEV\webview-example)
    Finished dev [unoptimized + debuginfo] target(s) in 0.71s
     Running `target\debug\webview-example.exe`
fatal runtime error: Rust cannot catch foreign exceptions
error: process didn't exit successfully: `target\debug\webview-example.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

I tested it with the code that included Pull Request #258, I don't think PR #258 has affected this error.

**Comment by zxey** [comment]
When using edge backend you unfortunately cannot load from a local file, because edge is sandboxed on Windows 10, you need to serve it through http server. Look at [actix example](https://github.com/Boscop/web-view/blob/master/examples/actix.rs), here you can see how to use `rust_embed` crate to embed files in you binary or load the from filesystem and then serve them with `actix`.

**Comment by Regentag** [comment]
@zxey Thank you for the answer. I'll try the `actix` example.
