### ISSUE TITLE
example of deployment with http server/files

### ISSUE THREAD

**Issue by FlowShowcontrol** [Boscop/web-view#53]
Hi,

great library! I am currently creating the front end in Vue JS. Now I am in development and I point the webview to localhost when the Vue JS dev server is on.

But now.. on to production. In the readme it says that local resources only work when using a http server to serve the files. However: how does one embed the files with a rust binary?

And if that is not possible, how can I use include_str! so that I don't get the "Local resource cannot be loaded" errors

Thanks

**Comment by green-s** [comment]
You could use [rust-embed](https://github.com/pyros2097/rust-embed) (or [includedir](https://github.com/tilpner/includedir) or [include_dir](https://github.com/Michael-F-Bryan/include_dir)), or tar/zip your files in your build script and embed with `include_bytes!`, then traverse/unpack at runtime. 

Then you set up the routing of your web server (e.g. [actix-web](https://actix.rs/docs/url-dispatch/)) to resolve to the embedded files. If using rust-embed you call `get(path)` on the generated struct. You could use [mime_guess](https://github.com/abonander/mime_guess) to set the content type.

It's probably only worth doing this for release builds since `include_*` macros can significantly increase compile times. AFAIK that's a compiler bug that may be fixed but for now I'm not sure there's much you can do apart from appending the files to the binary somehow.

**Comment by passy** [comment]
Depending on how many resources you have, you may be able to get away with just inlining them manually. In my case I could just use base64 data URIs and `include_str!` the HTML file. But if you require a build step for your JS, @green-s's option sounds great.
