### ISSUE TITLE
RPC from elm/yew

### ISSUE THREAD

**Issue by jonblack** [Boscop/web-view#57]
How do you make an RPC call between the rust code and elm or yew frontend code? The elm example doesn't show this, and as far as I can tell it's not possible to call `window.external.invoke` from either of these libraries.

**Comment by zxey** [comment]
I addressed the elm part in todo-elm example.
As for yew, see their example on asynchronous js callbacks [here](https://github.com/yewstack/yew/tree/master/examples/js_callback).
Hopefully this helped you a bit.
I will close this issue because the only thing remaining is to showcase yew, and there is a separate issue for that #66.
