### ISSUE TITLE
TODO example is slightly broken.

### ISSUE THREAD

**Issue by quadrupleslap** [Boscop/web-view#6]
Putting the characters from http://timelessrepo.com/json-isnt-a-javascript-subset into your todo example break it, because it uses serde_json to pass strings to the javascript, and json isn't a subset of javascript.

**Comment by Boscop** [comment]
Thanks for bringing this to my attention, I wasn't aware of this problem.
So it's just those 4 chars that prevent it from being a subset, right?

But I think the todo example doesn't have to accommodate this because it's just a very basic incomplete example, not a real world app, and should only include code that is relevant for learning how to use web-view (to avoid distracting the reader) :)
