### ISSUE TITLE
Forking webview

### ISSUE THREAD

**Issue by Freaky** [Boscop/web-view#64]
Given the upstream library is currently unmaintained, I think we should be looking at maintaining our own fork, so the crate is actually usable.

Most obviously for me, file dialogs don't work properly on Windows because of two uninitialized variables - a fix that could scarcely be more trivial.

I currently maintain [my own fork](https://github.com/Freaky/webview/commits/various-fixes) for [Compactor](https://github.com/Freaky/webview/commits/various-fixes) that fixes this and various other things - memory leaks, missed allocation checks, lack of error checking in the message loop, and trims some unnecessary allocations.

Checking this out manually and setting an env var to override is fragile and annoying, so I also have a fork of this create that exists entirely to point to my webview fork.  This is also less than ideal, and it's already spread to at least [one other project](https://github.com/prixt/soundsense-rs).

Shall we nip this in the bud?

**Comment by zxey** [comment]
Just yesterday I created a fork, where I fixed some uninitialized variables, so dialogs should work now. We should maybe just create an organization and put some common fork there so we can all contribute to it instead of maintaining separate forks.
I missed your fork when looking for suitable alternative for zserge/webview, so maybe we should just switch to that.
What do you think?

**Comment by zxey** [comment]
@Boscop could we create and organization move this repo over and create a fork of zserge/webview there?

**Comment by zxey** [comment]
I just updated web-view to use your fork, it's got some nice fixes.

**Comment by green-s** [comment]
> Also sometime in the future we could look into rewriting some platforms for webview in rust, the library is not that big and we would maintain only one codebase.

I started attempting this for the windows backend just a week ago, although from scratch rather than as a fork of this. I figured that the description of this crate being "bindings for the webview library" meant that a rewrite might not be welcomed, but if everyone's cool with making this more of a standalone thing then I could carry on in a branch instead.

Considering that the original library seems all but abandoned, with 133 open issues and 23 PRs, I don't think many users would object to the change in direction?

**Comment by zxey** [comment]
Sure, go ahead, I would welcome such a PR. I don't think people really mind if it is bindings or pure Rust (IMHO). I think that we could embed webview.h into this repository instead of using submodule and rewrite parts of it as needed. It was nice that we could take webview.h library and use it as is, but now that we have to maintain it, we can just use Rust.

**Comment by erlend-sh** [comment]
For the record, this all sounds like great news as far as the Amethyst team is concerned. We’ve been somewhat blocked on webview’s stagnation as well:

https://github.com/amethyst/atelier-editor/issues/20

👍 for
- starting an org for web-view and friends
- keep an actively developed fork of webview in said org
- gradually rewrite parts in Rust

**Comment by erlend-sh** [comment]
> could we create and organization move this repo over and create a fork of zserge/webview there?

Maybe that org already exists in https://github.com/tauri-apps/tauri

Operating as an org isn't without its challenges, so the fact that Tauri has already made a lot of headway in figuring out their basic governance model makes it a very suitable host.

**Comment by nothingismagick** [comment]
Hey, I'm from the open-source SFOSC-friendly tauri-apps project, and we've made some decent headway on sorting out the nightmare that is MSHTML in the original project by Zserge (which is most definitely not his fault, it was a great start!). We've still got a ways to go, so don't get your hopes up that it will be ready tomorrow. But soon :tm:!

We absolutely stand by our commitment to maintain not only the rust bindings to webview, but also webview itself - and this includes both MSHTML and CHAKRA support, tray interactions, easy app menus etc.

Having the community rally together to get this sorted, cleaned up (and moved to Rust where feasible) would be absolutely brilliant, and we'd be honoured to carry the torch.

**Comment by lucasfernog** [comment]
I'm working with @nothingismagick on Tauri and we just love the work from Boscop and Zserge, it really opens the gate for some very cool apps, and we're working to extend that with Tauri. So far we managed to do some cool stuff with webview, and now we're trying to merge some work from zserge's `webview-x` branch, moving away from MSHTML.

I'm sure that together we can push this to another level, the Tauri community is growing, and its going to be very cool. Make sure you guys check it out, we can figure it out together.

**Comment by nothingismagick** [comment]
Tauri has a Discord server, which you are all welcome to visit. There is already a working group for tech, but I'll make a temporary WG for web-view.

Perhaps we can coordinate a meeting time and talk about how we can best move this forward. Sometime this week would be great (Tue, Wed, Thur).

https://discord.gg/SpmNs4S

**Comment by zxey** [comment]
So I've decided to include webview.h directly into this repository instead of maintaining separate fork of zserge/webview.

This will allow us to gradually rewrite parts of webview in Rust as needed (which some people seem to be interested in).

I took an inspiration from successul rewrites such as GNOME/librsvg library and ongoing rewrite of bzip2 library, both from [Frederico Mena-Quintero](https://people.gnome.org/~federico/blog/bzip2-in-rust-basic-infra.html).

The tauri project looks cool (and very ambitious - in a good way), but it also seems to be much more than web-view, it is a framework. I would like to keep web-view simple and as small as possible, with very few dependencies, so projects like [tauri](https://github.com/tauri-apps/tauri) and [neutrino](https://github.com/alexislozano/neutrino/) are possible and can be built on top of web-view.

As for the included webview.h, I took the latest changes from [Freaky's fork at various-fixes](https://github.com/Freaky/webview/commits/various-fixes) branch, which was used previously. Feel free to create PRs directly here, if you want your changes included.

In the future we can possibly create some common repo where all the fixes for zserge/webview can live, [tauri](https://github.com/tauri-apps/tauri) has webview.h embedded directly in the source tree also, so we cannot use that directly (yet).

As for MSHTML vs EdgeHTML, I would like to keep MSHTML for as long as possible and create EdgeHTML alongside that which can be enabled with feature flag. The reason is that Rust supports Windows 7 and newer (AFAIK) and EdgeHTML supports Windows 10 only.

Thank you all for you interest, especially @Freaky for igniting this conversation and their fixes to webview and @green-s for their rewrite with builder pattern and documentation.

I am going to close this issue, but feel free to leave more comments or open new issues if you have any questions or suggestions.

**Comment by nothingismagick** [comment]
Right, we embedded it in the source tree, but that is a matter of history -
not anything permanently set in stone. We can definitely hoist it upwards.

And going forward, what the tauri org can commit to that a sole developer
cannot is that bus factor and transparency are guaranteed. We would gladly
make you co-owner of that repository as well...

>

**Comment by Boscop** [comment]
@zxey I agree that web-view should try to stay lean so that frameworks like tauri can be built on top of it, and that MSHTML should be supported as long as possible because some people are still using Windows 8.1 (e.g. me). But of course it would be great to be able to run Wasm apps in web-view (fullstack Rust with typesafe communication between backend and frontend).
@quadrupleslap Maybe we can somehow integrate the work that has been done on tether? Like merging both crates into one, that uses EdgeHTML where it's available, with MSHTML as fallback (but this fallback at runtime would require embedding a wasm-to-js compiled version of the app, which would run slower).

It would also be desirable to be able to create child windows. One use case where that's required is when writing GUIs for VST (audio) plugins where the host provides the parent window pointer, and the plugin HAS to create its window as a child of it.
Btw: There is [another crate](https://github.com/vanderlokken/rust-vst-gui) that uses MSHTML and supports the creation of child windows, I built a VST using this crate:
![image](https://user-images.githubusercontent.com/535593/48801114-d0e6a600-ed0b-11e8-9f1d-4f68046fa731.png)
We could also take inspiration from that, so that we have one combined crate that supports MSHTML, Wasm and the creation of child windows.
