### ISSUE TITLE
Add a string escaping function.

### ISSUE THREAD

**Issue by quadrupleslap** [Boscop/web-view#7]
#6 shows that there's a very obvious need to escape strings before passing them to Javascript, that's not fulfilled by a library like serde_json. So I think it'd be useful to add one to this library, so that users are less likely to accidentally introduce edge cases like that into their own apps.

You *could* include [the one from my ripoff of this library](https://github.com/quadrupleslap/tether/blob/master/src/escape.rs). :)

**Comment by Boscop** [comment]
Sorry, I was quite busy this week...
Thanks for this issue!

Yes, it makes sense to have such a string escaping function..
If you want, we can merge our two libraries into one, so we don't have to duplicate work :)
I also planned to have a builder API for this lib, and to add Edge support so that we can use Rust/Wasm in the frontend (with MSHTML as fallback)..

**Comment by quadrupleslap** [comment]
That's a good idea, but maintaining both a trait-based `Handler` API, and a function-based API in the same crate sounds difficult.

**Comment by Boscop** [comment]
Yea, I meant, I plan to have a Builder API instead of the `run()` function..

**Comment by quadrupleslap** [comment]
Sorry for misunderstanding - that sounds good! So what would needs to change from what [quadrupleslap/tether](https://github.com/quadrupleslap/tether) does, aside from Internet Explorer support?

**Comment by Boscop** [comment]
Sorry for taking so long to respond. My life is super busy right now..

I think it would be useful to merge our libraries so that there is one go-to library for this use case that is as convenient to use as possible, which supports Edge with IE as fallback (many people have IE installed but don't want to install Edge), with Builder API, urlencoding and that string escaping function etc.
If we agree on this "vision", I can give you co-maintainer access to this repo, then you have all the freedom to change the things you consider necessary..
What do you think? :)

(I will have more time again in April, but I'm still very busy until the end of March.)

**Comment by quadrupleslap** [comment]
Sure! Convenience and compatibility are great priorities to have.

**Comment by Boscop** [comment]
@quadrupleslap I added you as a collaborator, did you notice? :)

**Comment by quadrupleslap** [comment]
Sorry, it got drowned in my inbox!

**Comment by quadrupleslap** [comment]
Done! Not sure if I should've just pushed it to master though.
